abbreviations = {
    "hlo": "hello",
    "was": "what's",
    "gud": "good",
    "brb": "be right back",
    "gtg": "got to go",
    "ttyl": "talk to you later",
    "idk": "I don't know",
    "ikr": "I know right",
    "smh": "shaking my head",
    "tbh": "to be honest",
    "imo": "in my opinion",
    "imho": "in my humble opinion",
    "btw": "by the way",
    "np": "no problem",
    "omw": "on my way",
    "lol": "laugh out loud",
    "lmao": "laughing my ass off",
    "rofl": "rolling on the floor laughing",
    "wyd": "what are you doing",
    "wbu": "what about you",
    "wby": "what about you",
    "hbu": "how about you",
    "ily": "I love you",
    "idc": "I don't care",
    "nvm": "never mind",
    "afaik": "as far as I know",
    "asap": "as soon as possible",
    "bbl": "be back later",
    "bff": "best friend forever",
    "bday": "birthday",
    "dm": "direct message",
    "fyi": "for your information",
    "gg": "good game",
    "irl": "in real life",
    "jk": "just kidding",
    "n/a": "not applicable",
    "nsfw": "not safe for work",
    "omg": "oh my god",
    "plz": "please",
    "rn": "right now",
    "thx": "thanks",
    "ty": "thank you",
    "yw": "you’re welcome",
    "uk": "you know",
    "yk": "you know",
    "u": "you",
    "": "you",
    "r": "are",
    "ur": "your",
    "bc": "because",
    "bcz": "because",
    "abt": "about",
    "cya": "see you",
    "gr8": "great",
    "gn": "good night",
    "gm": "good morning",
    "wdym": "what do you mean",
    "wym": "what you mean",
    "fr": "for real",
    "ngl": "not gonna lie",
    "sus": "suspicious",
    "nah": "no",
    "ye": "yeah",
    "ya": "yeah",
    "yea": "yeah",
    "nope": "no",
    "yup": "yes",
    "coz": "because",
    "lemme": "let me",
    "gimme": "give me",
    "gotcha": "got you",
    "aint": "is not",
    "im": "I am",
    "ive": "I have",
    "idk": "I don't know",
    "w/e": "whatever",
    "ttys": "talk to you soon",
    "tbf": "to be fair",
    "b4": "before",
    "bday": "birthday",
    "hbd": "happy birthday",
    "tysm": "thank you so much",
    "np": "no problem",
    "ikr": "I know right",
    "wya": "where you at",
    "oml": "oh my lord",
    "ffs": "for fuck’s sake",
    "afaik": "as far as I know",
    "lmk": "let me know",
    "idc": "I don't care",
    "sup": "what’s up",
    "ya'll": "you all",
    "y'all": "you all",
    "tf": "the fuck",
    "tbhh": "to be very honest",
    "wyd?": "what are you doing?",
    "nm": "nothing much",
    "afaik": "as far as I know",
    "afk": "away from keyboard",
    "asap": "as soon as possible",
    "atm": "at the moment",
    "bbl": "be back later",
    "bc": "because",
    "bcoz": "because",
    "bday": "birthday",
    "brb": "be right back",
    "btw": "by the way",
    "b4": "before",
    "cya": "see you",
    "cu": "see you",
    "cud": "could",
    "cuz": "because",
    "dm": "direct message",
    "dnd": "do not disturb",
    "dunno": "don't know",
    "ez": "easy",
    "faq": "frequently asked questions",
    "fomo": "fear of missing out",
    "ftw": "for the win",
    "fyi": "for your information",
    "g2g": "got to go",
    "gg": "good game",
    "gm": "good morning",
    "gn": "good night",
    "gr8": "great",
    "gtg": "got to go",
    "hbd": "happy birthday",
    "hbu": "how about you",
    "hmu": "hit me up",
    "idc": "I don't care",
    "idk": "I don't know",
    "ikr": "I know right",
    "ily": "I love you",
    "imho": "in my humble opinion",
    "imo": "in my opinion",
    "irl": "in real life",
    "jic": "just in case",
    "jk": "just kidding",
    "k": "okay",
    "kewl": "cool",
    "l8r": "later",
    "lmao": "laughing my ass off",
    "lmk": "let me know",
    "lol": "laugh out loud",
    "msg": "message",
    "nbd": "no big deal",
    "nvm": "never mind",
    "np": "no problem",
    "nvr": "never",
    "omg": "oh my god",
    "omw": "on my way",
    "ootd": "outfit of the day",
    "pls": "please",
    "plz": "please",
    "plss": "please",
    "ppl": "people",
    "pov": "point of view",
    "rip": "rest in peace",
    "rn": "right now",
    "rofl": "rolling on the floor laughing",
    "rsvp": "please respond",
    "sry": "sorry",
    "smh": "shaking my head",
    "ssup": "what's up",
    "sup": "what's up",
    "tba": "to be announced",
    "tbh": "to be honest",
    "tbt": "throwback Thursday",
    "tfw": "that feeling when",
    "thx": "thanks",
    "tia": "thanks in advance",
    "tldr": "too long; didn't read",
    "ttyl": "talk to you later",
    "ty": "thank you",
    "u": "you",
    "ur": "your",
    "vibe": "atmosphere",
    "vip": "very important person",
    "w8": "wait",
    "wb": "welcome back",
    "wbu": "what about you",
    "wdym": "what do you mean",
    "wfh": "work from home",
    "wru": "where are you",
    "wtf": "what the heck",
    "wth": "what the heck",
    "wya": "where you at",
    "wyd": "what are you doing",
    "yolo": "you only live once",
    "yo": "hello",
    "yw": "you're welcome",
    "wsg": "what's up"
}


