pattern_expansions = {
    r"pl[sz]+": "please",
    r"thx+": "thanks",
    r"ty+": "thank you",
    r"noo+": "no",
    r"ye+s+": "yes",
    r"he+y+": "hey",
    r"hi+[iy]+": "hi",
    r"by+ee*": "bye",
    r"om+g+": "oh my god",
    r"smh+": "shaking my head",
    r"l+o+l+": "laughing out loud",
    r"ro+fl+": "rolling on the floor laughing",
    r"wt+f+": "what the heck",
    r"n+vm+": "never mind",
    r"gr+8": "great",
    r"so+r+y+": "sorry",
    r"co+o+l+": "cool",
    r"cu+z+": "because",
    r"cya+": "see you",
    r"h+mu+": "hit me up",
    r"g+tg+": "got to go",
    r"b+rb+": "be right back",
    r"ily+": "I love you",
    r"idk+": "I don't know",
    r"ikr+": "I know right",
    r"g+nn+": "good night",
    r"g+mm+": "good morning",
    r"t+b+h+": "to be honest",
    r"w+yd+": "what are you doing",
    r"w+bu+": "what about you",
    r"w+ya+": "where you at",
    r"w+ru+": "where are you",
    r"b+ae+": "baby",
    r"ya+ss+": "yes",
    r"eh+": "eh",
    r"ug+h+": "ugh",
    r"fr+": "for real"
}
